/* tslint:disable */
/* eslint-disable */
/**
 * Phase Two Admin REST API
 * This is a REST API reference for the Phase Two Keycloak custom resources. These are extensions to the standard [Keycloak Admin REST API](https://www.keycloak.org/docs-api/latest/rest-api/index.html).  ### Base URI format Paths specified in the documentation are relative to the the base URI. - Format: `https://<host>:<port>/auth/realms` - Example: `https://app.phasetwo.io/auth/realms`  ### Authentication Authentication is achieved by using the `Authentication: Bearer <token>` header in all requests. This is either the access token received from a normal authentication, or by a request directly to the OpenID Connect token endpoint.  It is recommended that you use a Keycloak Admin Client, such as [this one for Javascript](https://github.com/keycloak/keycloak/tree/main/js/libs/keycloak-admin-client), as they take care of authentication, getting an access token, and refreshing it when it expires.  #### Client credentials grant example ``` POST /auth/realms/test-realm/protocol/openid-connect/token Host: app.phasetwo.io Accept: application/json Content-type: application/x-www-form-urlencoded  grant_type=client_credentials&client_id=admin-cli&client_secret=fd649804-3a74-4d69-acaa-8f065c6b7da1 ```  #### Password grant example ``` POST /auth/realms/test-realm/protocol/openid-connect/token Host: app.phasetwo.io Accept: application/json Content-type: application/x-www-form-urlencoded  grant_type=password&username=uname@foo.com&password=pwd123AZY&client_id=admin-cli ```  ### SDKs Modern API libraries are available for several common languages. These are available as open source at the links below, or you can choose to generate your own using our [OpenAPI spec file](https://raw.githubusercontent.com/p2-inc/phasetwo-docs/main/openapi.yaml).  | Language | Library | | --- | --- | | Java (and other JVM langs) | https://github.com/p2-inc/phasetwo-java | | JavaScript/TypeScript | https://github.com/p2-inc/phasetwo-js | | Python | https://github.com/p2-inc/phasetwo-python | 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type IdentityProviderMapperRepresentation,
    IdentityProviderMapperRepresentationFromJSON,
    IdentityProviderMapperRepresentationToJSON,
} from '../models/IdentityProviderMapperRepresentation';
import {
    type IdentityProviderRepresentation,
    IdentityProviderRepresentationFromJSON,
    IdentityProviderRepresentationToJSON,
} from '../models/IdentityProviderRepresentation';
import {
    type LinkIdentityProviderRepresentation,
    LinkIdentityProviderRepresentationFromJSON,
    LinkIdentityProviderRepresentationToJSON,
} from '../models/LinkIdentityProviderRepresentation';

export interface AddIdpMapperRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * 
     */
    alias: string;
    /**
     * 
     */
    identityProviderMapperRepresentation: IdentityProviderMapperRepresentation;
}

export interface CreateIdpRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * 
     */
    identityProviderRepresentation: IdentityProviderRepresentation;
}

export interface DeleteIdpRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * Identity Provider alias
     */
    alias: string;
}

export interface DeleteIdpMapperRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * 
     */
    alias: string;
    /**
     * Mapper id
     */
    id: string;
}

export interface GetIdpRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * Identity Provider alias
     */
    alias: string;
}

export interface GetIdpMapperRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * 
     */
    alias: string;
    /**
     * Mapper id
     */
    id: string;
}

export interface GetIdpMappersRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * 
     */
    alias: string;
}

export interface GetIdpsRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
}

export interface ImportIdpJsonRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
}

export interface LinkIdpRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * 
     */
    linkIdentityProviderRepresentation: LinkIdentityProviderRepresentation;
}

export interface UnlinkIdpRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * idp alias
     */
    alias: string;
}

export interface UpdateIdpRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * Identity Provider alias
     */
    alias: string;
    /**
     * 
     */
    identityProviderRepresentation: IdentityProviderRepresentation;
}

export interface UpdateIdpMapperRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * 
     */
    alias: string;
    /**
     * Mapper id
     */
    id: string;
    /**
     * 
     */
    identityProviderMapperRepresentation: IdentityProviderMapperRepresentation;
}

/**
 * 
 */
export class IdentityProvidersApi extends runtime.BaseAPI {

    /**
     * Creates request options for addIdpMapper without sending the request
     */
    async addIdpMapperRequestOpts(requestParameters: AddIdpMapperRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling addIdpMapper().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling addIdpMapper().'
            );
        }

        if (requestParameters['alias'] == null) {
            throw new runtime.RequiredError(
                'alias',
                'Required parameter "alias" was null or undefined when calling addIdpMapper().'
            );
        }

        if (requestParameters['identityProviderMapperRepresentation'] == null) {
            throw new runtime.RequiredError(
                'identityProviderMapperRepresentation',
                'Required parameter "identityProviderMapperRepresentation" was null or undefined when calling addIdpMapper().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/idps/{alias}/mappers`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{alias}', encodeURIComponent(String(requestParameters['alias'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IdentityProviderMapperRepresentationToJSON(requestParameters['identityProviderMapperRepresentation']),
        };
    }

    /**
     * Add a mapper to identity provider
     */
    async addIdpMapperRaw(requestParameters: AddIdpMapperRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.addIdpMapperRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Add a mapper to identity provider
     */
    async addIdpMapper(requestParameters: AddIdpMapperRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.addIdpMapperRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for createIdp without sending the request
     */
    async createIdpRequestOpts(requestParameters: CreateIdpRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling createIdp().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling createIdp().'
            );
        }

        if (requestParameters['identityProviderRepresentation'] == null) {
            throw new runtime.RequiredError(
                'identityProviderRepresentation',
                'Required parameter "identityProviderRepresentation" was null or undefined when calling createIdp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/idps`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IdentityProviderRepresentationToJSON(requestParameters['identityProviderRepresentation']),
        };
    }

    /**
     * Create a new identity provider for this organization
     */
    async createIdpRaw(requestParameters: CreateIdpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.createIdpRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a new identity provider for this organization
     */
    async createIdp(requestParameters: CreateIdpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createIdpRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteIdp without sending the request
     */
    async deleteIdpRequestOpts(requestParameters: DeleteIdpRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling deleteIdp().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling deleteIdp().'
            );
        }

        if (requestParameters['alias'] == null) {
            throw new runtime.RequiredError(
                'alias',
                'Required parameter "alias" was null or undefined when calling deleteIdp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/idps/{alias}`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{alias}', encodeURIComponent(String(requestParameters['alias'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete the identity provider
     */
    async deleteIdpRaw(requestParameters: DeleteIdpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteIdpRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete the identity provider
     */
    async deleteIdp(requestParameters: DeleteIdpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteIdpRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteIdpMapper without sending the request
     */
    async deleteIdpMapperRequestOpts(requestParameters: DeleteIdpMapperRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling deleteIdpMapper().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling deleteIdpMapper().'
            );
        }

        if (requestParameters['alias'] == null) {
            throw new runtime.RequiredError(
                'alias',
                'Required parameter "alias" was null or undefined when calling deleteIdpMapper().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteIdpMapper().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/idps/{alias}/mappers/{id}`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{alias}', encodeURIComponent(String(requestParameters['alias'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a mapper for the identity provider
     */
    async deleteIdpMapperRaw(requestParameters: DeleteIdpMapperRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteIdpMapperRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a mapper for the identity provider
     */
    async deleteIdpMapper(requestParameters: DeleteIdpMapperRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteIdpMapperRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getIdp without sending the request
     */
    async getIdpRequestOpts(requestParameters: GetIdpRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling getIdp().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling getIdp().'
            );
        }

        if (requestParameters['alias'] == null) {
            throw new runtime.RequiredError(
                'alias',
                'Required parameter "alias" was null or undefined when calling getIdp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/idps/{alias}`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{alias}', encodeURIComponent(String(requestParameters['alias'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get identity provider for this organization by alias
     */
    async getIdpRaw(requestParameters: GetIdpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IdentityProviderRepresentation>> {
        const requestOptions = await this.getIdpRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IdentityProviderRepresentationFromJSON(jsonValue));
    }

    /**
     * Get identity provider for this organization by alias
     */
    async getIdp(requestParameters: GetIdpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IdentityProviderRepresentation> {
        const response = await this.getIdpRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getIdpMapper without sending the request
     */
    async getIdpMapperRequestOpts(requestParameters: GetIdpMapperRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling getIdpMapper().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling getIdpMapper().'
            );
        }

        if (requestParameters['alias'] == null) {
            throw new runtime.RequiredError(
                'alias',
                'Required parameter "alias" was null or undefined when calling getIdpMapper().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getIdpMapper().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/idps/{alias}/mappers/{id}`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{alias}', encodeURIComponent(String(requestParameters['alias'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get mapper by id for the identity provider
     */
    async getIdpMapperRaw(requestParameters: GetIdpMapperRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IdentityProviderMapperRepresentation>> {
        const requestOptions = await this.getIdpMapperRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IdentityProviderMapperRepresentationFromJSON(jsonValue));
    }

    /**
     * Get mapper by id for the identity provider
     */
    async getIdpMapper(requestParameters: GetIdpMapperRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IdentityProviderMapperRepresentation> {
        const response = await this.getIdpMapperRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getIdpMappers without sending the request
     */
    async getIdpMappersRequestOpts(requestParameters: GetIdpMappersRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling getIdpMappers().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling getIdpMappers().'
            );
        }

        if (requestParameters['alias'] == null) {
            throw new runtime.RequiredError(
                'alias',
                'Required parameter "alias" was null or undefined when calling getIdpMappers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/idps/{alias}/mappers`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{alias}', encodeURIComponent(String(requestParameters['alias'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get mappers for identity provider
     */
    async getIdpMappersRaw(requestParameters: GetIdpMappersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<IdentityProviderMapperRepresentation>>> {
        const requestOptions = await this.getIdpMappersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(IdentityProviderMapperRepresentationFromJSON));
    }

    /**
     * Get mappers for identity provider
     */
    async getIdpMappers(requestParameters: GetIdpMappersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<IdentityProviderMapperRepresentation>> {
        const response = await this.getIdpMappersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getIdps without sending the request
     */
    async getIdpsRequestOpts(requestParameters: GetIdpsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling getIdps().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling getIdps().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/idps`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get identity providers for this organization
     */
    async getIdpsRaw(requestParameters: GetIdpsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<IdentityProviderRepresentation>>> {
        const requestOptions = await this.getIdpsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(IdentityProviderRepresentationFromJSON));
    }

    /**
     * Get identity providers for this organization
     */
    async getIdps(requestParameters: GetIdpsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<IdentityProviderRepresentation>> {
        const response = await this.getIdpsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for importIdpJson without sending the request
     */
    async importIdpJsonRequestOpts(requestParameters: ImportIdpJsonRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling importIdpJson().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling importIdpJson().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/idps/import-config`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Import identity provider from uploaded JSON file
     */
    async importIdpJsonRaw(requestParameters: ImportIdpJsonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.importIdpJsonRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Import identity provider from uploaded JSON file
     */
    async importIdpJson(requestParameters: ImportIdpJsonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.importIdpJsonRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for linkIdp without sending the request
     */
    async linkIdpRequestOpts(requestParameters: LinkIdpRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling linkIdp().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling linkIdp().'
            );
        }

        if (requestParameters['linkIdentityProviderRepresentation'] == null) {
            throw new runtime.RequiredError(
                'linkIdentityProviderRepresentation',
                'Required parameter "linkIdentityProviderRepresentation" was null or undefined when calling linkIdp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/idps/link`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LinkIdentityProviderRepresentationToJSON(requestParameters['linkIdentityProviderRepresentation']),
        };
    }

    /**
     * Link an existing identity provider to this organization
     */
    async linkIdpRaw(requestParameters: LinkIdpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.linkIdpRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Link an existing identity provider to this organization
     */
    async linkIdp(requestParameters: LinkIdpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.linkIdpRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for unlinkIdp without sending the request
     */
    async unlinkIdpRequestOpts(requestParameters: UnlinkIdpRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling unlinkIdp().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling unlinkIdp().'
            );
        }

        if (requestParameters['alias'] == null) {
            throw new runtime.RequiredError(
                'alias',
                'Required parameter "alias" was null or undefined when calling unlinkIdp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/idps/{alias}/unlink`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{alias}', encodeURIComponent(String(requestParameters['alias'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Unlink an existing and linked identity provider from this organization
     */
    async unlinkIdpRaw(requestParameters: UnlinkIdpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.unlinkIdpRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Unlink an existing and linked identity provider from this organization
     */
    async unlinkIdp(requestParameters: UnlinkIdpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.unlinkIdpRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for updateIdp without sending the request
     */
    async updateIdpRequestOpts(requestParameters: UpdateIdpRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling updateIdp().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling updateIdp().'
            );
        }

        if (requestParameters['alias'] == null) {
            throw new runtime.RequiredError(
                'alias',
                'Required parameter "alias" was null or undefined when calling updateIdp().'
            );
        }

        if (requestParameters['identityProviderRepresentation'] == null) {
            throw new runtime.RequiredError(
                'identityProviderRepresentation',
                'Required parameter "identityProviderRepresentation" was null or undefined when calling updateIdp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/idps/{alias}`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{alias}', encodeURIComponent(String(requestParameters['alias'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: IdentityProviderRepresentationToJSON(requestParameters['identityProviderRepresentation']),
        };
    }

    /**
     * Update identity provider for this organization by alias
     */
    async updateIdpRaw(requestParameters: UpdateIdpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.updateIdpRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update identity provider for this organization by alias
     */
    async updateIdp(requestParameters: UpdateIdpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateIdpRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for updateIdpMapper without sending the request
     */
    async updateIdpMapperRequestOpts(requestParameters: UpdateIdpMapperRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling updateIdpMapper().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling updateIdpMapper().'
            );
        }

        if (requestParameters['alias'] == null) {
            throw new runtime.RequiredError(
                'alias',
                'Required parameter "alias" was null or undefined when calling updateIdpMapper().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateIdpMapper().'
            );
        }

        if (requestParameters['identityProviderMapperRepresentation'] == null) {
            throw new runtime.RequiredError(
                'identityProviderMapperRepresentation',
                'Required parameter "identityProviderMapperRepresentation" was null or undefined when calling updateIdpMapper().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/idps/{alias}/mappers/{id}`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{alias}', encodeURIComponent(String(requestParameters['alias'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: IdentityProviderMapperRepresentationToJSON(requestParameters['identityProviderMapperRepresentation']),
        };
    }

    /**
     * Update a mapper for the identity provider
     */
    async updateIdpMapperRaw(requestParameters: UpdateIdpMapperRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.updateIdpMapperRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update a mapper for the identity provider
     */
    async updateIdpMapper(requestParameters: UpdateIdpMapperRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateIdpMapperRaw(requestParameters, initOverrides);
    }

}
