/* tslint:disable */
/* eslint-disable */
/**
 * Phase Two Admin REST API
 * This is a REST API reference for the Phase Two Keycloak custom resources. These are extensions to the standard [Keycloak Admin REST API](https://www.keycloak.org/docs-api/latest/rest-api/index.html).  ### Base URI format Paths specified in the documentation are relative to the the base URI. - Format: `https://<host>:<port>/auth/realms` - Example: `https://app.phasetwo.io/auth/realms`  ### Authentication Authentication is achieved by using the `Authentication: Bearer <token>` header in all requests. This is either the access token received from a normal authentication, or by a request directly to the OpenID Connect token endpoint.  It is recommended that you use a Keycloak Admin Client, such as [this one for Javascript](https://github.com/keycloak/keycloak/tree/main/js/libs/keycloak-admin-client), as they take care of authentication, getting an access token, and refreshing it when it expires.  #### Client credentials grant example ``` POST /auth/realms/test-realm/protocol/openid-connect/token Host: app.phasetwo.io Accept: application/json Content-type: application/x-www-form-urlencoded  grant_type=client_credentials&client_id=admin-cli&client_secret=fd649804-3a74-4d69-acaa-8f065c6b7da1 ```  #### Password grant example ``` POST /auth/realms/test-realm/protocol/openid-connect/token Host: app.phasetwo.io Accept: application/json Content-type: application/x-www-form-urlencoded  grant_type=password&username=uname@foo.com&password=pwd123AZY&client_id=admin-cli ```  ### SDKs Modern API libraries are available for several common languages. These are available as open source at the links below, or you can choose to generate your own using our [OpenAPI spec file](https://raw.githubusercontent.com/p2-inc/phasetwo-docs/main/openapi.yaml).  | Language | Library | | --- | --- | | Java (and other JVM langs) | https://github.com/p2-inc/phasetwo-java | | JavaScript/TypeScript | https://github.com/p2-inc/phasetwo-js | | Python | https://github.com/p2-inc/phasetwo-python | 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type BulkResponseItem,
    BulkResponseItemFromJSON,
    BulkResponseItemToJSON,
} from '../models/BulkResponseItem';
import {
    type OrganizationRoleRepresentation,
    OrganizationRoleRepresentationFromJSON,
    OrganizationRoleRepresentationToJSON,
} from '../models/OrganizationRoleRepresentation';
import {
    type UserRepresentation,
    UserRepresentationFromJSON,
    UserRepresentationToJSON,
} from '../models/UserRepresentation';

export interface CheckUserOrganizationRoleRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * organization role name
     */
    name: string;
    /**
     * user id
     */
    userId: string;
}

export interface CreateOrganizationRoleRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * 
     */
    organizationRoleRepresentation: OrganizationRoleRepresentation;
}

export interface CreateOrganizationRolesRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * 
     */
    organizationRoleRepresentation: Array<OrganizationRoleRepresentation>;
}

export interface DeleteOrganizationRoleRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * organization role name
     */
    name: string;
}

export interface DeleteOrganizationRolesRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * 
     */
    organizationRoleRepresentation: Array<OrganizationRoleRepresentation>;
}

export interface GetOrganizationRoleRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * organization role name
     */
    name: string;
}

export interface GetOrganizationRolesRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
}

export interface GetUserOrganizationRolesRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * organization role name
     */
    name: string;
}

export interface GrantUserOrganizationRoleRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * organization role name
     */
    name: string;
    /**
     * user id
     */
    userId: string;
}

export interface RevokeUserOrganizationRoleRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * organization role name
     */
    name: string;
    /**
     * user id
     */
    userId: string;
}

export interface UpdateOrganizationRoleRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * organization role name
     */
    name: string;
    /**
     * 
     */
    organizationRoleRepresentation: OrganizationRoleRepresentation;
}

/**
 * 
 */
export class OrganizationRolesApi extends runtime.BaseAPI {

    /**
     * Creates request options for checkUserOrganizationRole without sending the request
     */
    async checkUserOrganizationRoleRequestOpts(requestParameters: CheckUserOrganizationRoleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling checkUserOrganizationRole().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling checkUserOrganizationRole().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling checkUserOrganizationRole().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling checkUserOrganizationRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/roles/{name}/users/{userId}`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{name}', encodeURIComponent(String(requestParameters['name'])));
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Check if a user has an organization role
     */
    async checkUserOrganizationRoleRaw(requestParameters: CheckUserOrganizationRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.checkUserOrganizationRoleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Check if a user has an organization role
     */
    async checkUserOrganizationRole(requestParameters: CheckUserOrganizationRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.checkUserOrganizationRoleRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for createOrganizationRole without sending the request
     */
    async createOrganizationRoleRequestOpts(requestParameters: CreateOrganizationRoleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling createOrganizationRole().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling createOrganizationRole().'
            );
        }

        if (requestParameters['organizationRoleRepresentation'] == null) {
            throw new runtime.RequiredError(
                'organizationRoleRepresentation',
                'Required parameter "organizationRoleRepresentation" was null or undefined when calling createOrganizationRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/roles`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OrganizationRoleRepresentationToJSON(requestParameters['organizationRoleRepresentation']),
        };
    }

    /**
     * Create a new role for this organization
     */
    async createOrganizationRoleRaw(requestParameters: CreateOrganizationRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.createOrganizationRoleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a new role for this organization
     */
    async createOrganizationRole(requestParameters: CreateOrganizationRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createOrganizationRoleRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for createOrganizationRoles without sending the request
     */
    async createOrganizationRolesRequestOpts(requestParameters: CreateOrganizationRolesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling createOrganizationRoles().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling createOrganizationRoles().'
            );
        }

        if (requestParameters['organizationRoleRepresentation'] == null) {
            throw new runtime.RequiredError(
                'organizationRoleRepresentation',
                'Required parameter "organizationRoleRepresentation" was null or undefined when calling createOrganizationRoles().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/roles`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['organizationRoleRepresentation']!.map(OrganizationRoleRepresentationToJSON),
        };
    }

    /**
     * Create new roles for this organization
     */
    async createOrganizationRolesRaw(requestParameters: CreateOrganizationRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BulkResponseItem>>> {
        const requestOptions = await this.createOrganizationRolesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BulkResponseItemFromJSON));
    }

    /**
     * Create new roles for this organization
     */
    async createOrganizationRoles(requestParameters: CreateOrganizationRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BulkResponseItem>> {
        const response = await this.createOrganizationRolesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteOrganizationRole without sending the request
     */
    async deleteOrganizationRoleRequestOpts(requestParameters: DeleteOrganizationRoleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling deleteOrganizationRole().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling deleteOrganizationRole().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling deleteOrganizationRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/roles/{name}`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{name}', encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete this organization role
     */
    async deleteOrganizationRoleRaw(requestParameters: DeleteOrganizationRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteOrganizationRoleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete this organization role
     */
    async deleteOrganizationRole(requestParameters: DeleteOrganizationRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteOrganizationRoleRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteOrganizationRoles without sending the request
     */
    async deleteOrganizationRolesRequestOpts(requestParameters: DeleteOrganizationRolesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling deleteOrganizationRoles().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling deleteOrganizationRoles().'
            );
        }

        if (requestParameters['organizationRoleRepresentation'] == null) {
            throw new runtime.RequiredError(
                'organizationRoleRepresentation',
                'Required parameter "organizationRoleRepresentation" was null or undefined when calling deleteOrganizationRoles().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/roles`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['organizationRoleRepresentation']!.map(OrganizationRoleRepresentationToJSON),
        };
    }

    /**
     * Delete this organization roles
     */
    async deleteOrganizationRolesRaw(requestParameters: DeleteOrganizationRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BulkResponseItem>>> {
        const requestOptions = await this.deleteOrganizationRolesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BulkResponseItemFromJSON));
    }

    /**
     * Delete this organization roles
     */
    async deleteOrganizationRoles(requestParameters: DeleteOrganizationRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BulkResponseItem>> {
        const response = await this.deleteOrganizationRolesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getOrganizationRole without sending the request
     */
    async getOrganizationRoleRequestOpts(requestParameters: GetOrganizationRoleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling getOrganizationRole().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling getOrganizationRole().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getOrganizationRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/roles/{name}`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{name}', encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get role for this organization by name
     */
    async getOrganizationRoleRaw(requestParameters: GetOrganizationRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizationRoleRepresentation>> {
        const requestOptions = await this.getOrganizationRoleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationRoleRepresentationFromJSON(jsonValue));
    }

    /**
     * Get role for this organization by name
     */
    async getOrganizationRole(requestParameters: GetOrganizationRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizationRoleRepresentation> {
        const response = await this.getOrganizationRoleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getOrganizationRoles without sending the request
     */
    async getOrganizationRolesRequestOpts(requestParameters: GetOrganizationRolesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling getOrganizationRoles().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling getOrganizationRoles().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/roles`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get roles for this organization
     */
    async getOrganizationRolesRaw(requestParameters: GetOrganizationRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OrganizationRoleRepresentation>>> {
        const requestOptions = await this.getOrganizationRolesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrganizationRoleRepresentationFromJSON));
    }

    /**
     * Get roles for this organization
     */
    async getOrganizationRoles(requestParameters: GetOrganizationRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OrganizationRoleRepresentation>> {
        const response = await this.getOrganizationRolesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getUserOrganizationRoles without sending the request
     */
    async getUserOrganizationRolesRequestOpts(requestParameters: GetUserOrganizationRolesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling getUserOrganizationRoles().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling getUserOrganizationRoles().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getUserOrganizationRoles().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/roles/{name}/users`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{name}', encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get users with this organization role
     */
    async getUserOrganizationRolesRaw(requestParameters: GetUserOrganizationRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserRepresentation>>> {
        const requestOptions = await this.getUserOrganizationRolesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserRepresentationFromJSON));
    }

    /**
     * Get users with this organization role
     */
    async getUserOrganizationRoles(requestParameters: GetUserOrganizationRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserRepresentation>> {
        const response = await this.getUserOrganizationRolesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for grantUserOrganizationRole without sending the request
     */
    async grantUserOrganizationRoleRequestOpts(requestParameters: GrantUserOrganizationRoleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling grantUserOrganizationRole().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling grantUserOrganizationRole().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling grantUserOrganizationRole().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling grantUserOrganizationRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/roles/{name}/users/{userId}`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{name}', encodeURIComponent(String(requestParameters['name'])));
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Grant the specified user to the specified organization role
     * Grant a user an organization role
     */
    async grantUserOrganizationRoleRaw(requestParameters: GrantUserOrganizationRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.grantUserOrganizationRoleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Grant the specified user to the specified organization role
     * Grant a user an organization role
     */
    async grantUserOrganizationRole(requestParameters: GrantUserOrganizationRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.grantUserOrganizationRoleRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for revokeUserOrganizationRole without sending the request
     */
    async revokeUserOrganizationRoleRequestOpts(requestParameters: RevokeUserOrganizationRoleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling revokeUserOrganizationRole().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling revokeUserOrganizationRole().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling revokeUserOrganizationRole().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling revokeUserOrganizationRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/roles/{name}/users/{userId}`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{name}', encodeURIComponent(String(requestParameters['name'])));
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Revoke the specified organization role from the specified user
     * Revoke an organization role from a user
     */
    async revokeUserOrganizationRoleRaw(requestParameters: RevokeUserOrganizationRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.revokeUserOrganizationRoleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Revoke the specified organization role from the specified user
     * Revoke an organization role from a user
     */
    async revokeUserOrganizationRole(requestParameters: RevokeUserOrganizationRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.revokeUserOrganizationRoleRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for updateOrganizationRole without sending the request
     */
    async updateOrganizationRoleRequestOpts(requestParameters: UpdateOrganizationRoleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling updateOrganizationRole().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling updateOrganizationRole().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling updateOrganizationRole().'
            );
        }

        if (requestParameters['organizationRoleRepresentation'] == null) {
            throw new runtime.RequiredError(
                'organizationRoleRepresentation',
                'Required parameter "organizationRoleRepresentation" was null or undefined when calling updateOrganizationRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/roles/{name}`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{name}', encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: OrganizationRoleRepresentationToJSON(requestParameters['organizationRoleRepresentation']),
        };
    }

    /**
     * Update role for this organization
     */
    async updateOrganizationRoleRaw(requestParameters: UpdateOrganizationRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.updateOrganizationRoleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update role for this organization
     */
    async updateOrganizationRole(requestParameters: UpdateOrganizationRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateOrganizationRoleRaw(requestParameters, initOverrides);
    }

}
