/* tslint:disable */
/* eslint-disable */
/**
 * Phase Two Admin REST API
 * This is a REST API reference for the Phase Two Keycloak custom resources. These are extensions to the standard [Keycloak Admin REST API](https://www.keycloak.org/docs-api/latest/rest-api/index.html).  ### Base URI format Paths specified in the documentation are relative to the the base URI. - Format: `https://<host>:<port>/auth/realms` - Example: `https://app.phasetwo.io/auth/realms`  ### Authentication Authentication is achieved by using the `Authentication: Bearer <token>` header in all requests. This is either the access token received from a normal authentication, or by a request directly to the OpenID Connect token endpoint.  It is recommended that you use a Keycloak Admin Client, such as [this one for Javascript](https://github.com/keycloak/keycloak/tree/main/js/libs/keycloak-admin-client), as they take care of authentication, getting an access token, and refreshing it when it expires.  #### Client credentials grant example ``` POST /auth/realms/test-realm/protocol/openid-connect/token Host: app.phasetwo.io Accept: application/json Content-type: application/x-www-form-urlencoded  grant_type=client_credentials&client_id=admin-cli&client_secret=fd649804-3a74-4d69-acaa-8f065c6b7da1 ```  #### Password grant example ``` POST /auth/realms/test-realm/protocol/openid-connect/token Host: app.phasetwo.io Accept: application/json Content-type: application/x-www-form-urlencoded  grant_type=password&username=uname@foo.com&password=pwd123AZY&client_id=admin-cli ```  ### SDKs Modern API libraries are available for several common languages. These are available as open source at the links below, or you can choose to generate your own using our [OpenAPI spec file](https://raw.githubusercontent.com/p2-inc/phasetwo-docs/main/openapi.yaml).  | Language | Library | | --- | --- | | Java (and other JVM langs) | https://github.com/p2-inc/phasetwo-java | | JavaScript/TypeScript | https://github.com/p2-inc/phasetwo-js | | Python | https://github.com/p2-inc/phasetwo-python | 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type OrganizationMemberAttributeRepresentation,
    OrganizationMemberAttributeRepresentationFromJSON,
    OrganizationMemberAttributeRepresentationToJSON,
} from '../models/OrganizationMemberAttributeRepresentation';
import {
    type UserWithOrgsBriefRepresentation,
    UserWithOrgsBriefRepresentationFromJSON,
    UserWithOrgsBriefRepresentationToJSON,
} from '../models/UserWithOrgsBriefRepresentation';

export interface AddOrganizationMemberRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * user id
     */
    userId: string;
}

export interface AddOrganizationMemberAttributesRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * user id
     */
    userId: string;
    /**
     * 
     */
    organizationMemberAttributeRepresentation: OrganizationMemberAttributeRepresentation;
}

export interface CheckOrganizationMembershipRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * user id
     */
    userId: string;
}

export interface GetOrganizationMemberAttributesRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * user id
     */
    userId: string;
}

export interface GetOrganizationMembershipsRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * 
     */
    search?: string;
    /**
     * 
     */
    first?: number;
    /**
     * 
     */
    max?: number;
    /**
     * 
     */
    excludeAdminAccounts?: boolean;
    /**
     * 
     */
    includeOrgs?: boolean;
}

export interface GetOrganizationMembershipsCountRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * 
     */
    excludeAdminAccounts?: boolean;
}

export interface RemoveOrganizationMemberRequest {
    /**
     * realm name (not id!)
     */
    realm: string;
    /**
     * organization id
     */
    orgId: string;
    /**
     * user id
     */
    userId: string;
}

/**
 * 
 */
export class OrganizationMembershipsApi extends runtime.BaseAPI {

    /**
     * Creates request options for addOrganizationMember without sending the request
     */
    async addOrganizationMemberRequestOpts(requestParameters: AddOrganizationMemberRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling addOrganizationMember().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling addOrganizationMember().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling addOrganizationMember().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/members/{userId}`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Add the specified user to the specified organization as a member
     * Add an organization member
     */
    async addOrganizationMemberRaw(requestParameters: AddOrganizationMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.addOrganizationMemberRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Add the specified user to the specified organization as a member
     * Add an organization member
     */
    async addOrganizationMember(requestParameters: AddOrganizationMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.addOrganizationMemberRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for addOrganizationMemberAttributes without sending the request
     */
    async addOrganizationMemberAttributesRequestOpts(requestParameters: AddOrganizationMemberAttributesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling addOrganizationMemberAttributes().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling addOrganizationMemberAttributes().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling addOrganizationMemberAttributes().'
            );
        }

        if (requestParameters['organizationMemberAttributeRepresentation'] == null) {
            throw new runtime.RequiredError(
                'organizationMemberAttributeRepresentation',
                'Required parameter "organizationMemberAttributeRepresentation" was null or undefined when calling addOrganizationMemberAttributes().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/members/{userId}/attributes`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: OrganizationMemberAttributeRepresentationToJSON(requestParameters['organizationMemberAttributeRepresentation']),
        };
    }

    /**
     * Add or update attributes for a specific member of an organization
     * Add/update organization member attributes
     */
    async addOrganizationMemberAttributesRaw(requestParameters: AddOrganizationMemberAttributesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: Array<string>; }>> {
        const requestOptions = await this.addOrganizationMemberAttributesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Add or update attributes for a specific member of an organization
     * Add/update organization member attributes
     */
    async addOrganizationMemberAttributes(requestParameters: AddOrganizationMemberAttributesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: Array<string>; }> {
        const response = await this.addOrganizationMemberAttributesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for checkOrganizationMembership without sending the request
     */
    async checkOrganizationMembershipRequestOpts(requestParameters: CheckOrganizationMembershipRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling checkOrganizationMembership().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling checkOrganizationMembership().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling checkOrganizationMembership().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/members/{userId}`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Check if a user is a member of an organization
     */
    async checkOrganizationMembershipRaw(requestParameters: CheckOrganizationMembershipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.checkOrganizationMembershipRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Check if a user is a member of an organization
     */
    async checkOrganizationMembership(requestParameters: CheckOrganizationMembershipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.checkOrganizationMembershipRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getOrganizationMemberAttributes without sending the request
     */
    async getOrganizationMemberAttributesRequestOpts(requestParameters: GetOrganizationMemberAttributesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling getOrganizationMemberAttributes().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling getOrganizationMemberAttributes().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getOrganizationMemberAttributes().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/members/{userId}/attributes`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get attributes for a specific member of an organization
     * Get organization member attributes
     */
    async getOrganizationMemberAttributesRaw(requestParameters: GetOrganizationMemberAttributesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: Array<string>; }>> {
        const requestOptions = await this.getOrganizationMemberAttributesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get attributes for a specific member of an organization
     * Get organization member attributes
     */
    async getOrganizationMemberAttributes(requestParameters: GetOrganizationMemberAttributesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: Array<string>; }> {
        const response = await this.getOrganizationMemberAttributesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getOrganizationMemberships without sending the request
     */
    async getOrganizationMembershipsRequestOpts(requestParameters: GetOrganizationMembershipsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling getOrganizationMemberships().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling getOrganizationMemberships().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['first'] != null) {
            queryParameters['first'] = requestParameters['first'];
        }

        if (requestParameters['max'] != null) {
            queryParameters['max'] = requestParameters['max'];
        }

        if (requestParameters['excludeAdminAccounts'] != null) {
            queryParameters['excludeAdminAccounts'] = requestParameters['excludeAdminAccounts'];
        }

        if (requestParameters['includeOrgs'] != null) {
            queryParameters['includeOrgs'] = requestParameters['includeOrgs'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/members`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a paginated list of users who are a member of the specified organization.
     * Get organization memberships
     */
    async getOrganizationMembershipsRaw(requestParameters: GetOrganizationMembershipsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserWithOrgsBriefRepresentation>>> {
        const requestOptions = await this.getOrganizationMembershipsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserWithOrgsBriefRepresentationFromJSON));
    }

    /**
     * Get a paginated list of users who are a member of the specified organization.
     * Get organization memberships
     */
    async getOrganizationMemberships(requestParameters: GetOrganizationMembershipsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserWithOrgsBriefRepresentation>> {
        const response = await this.getOrganizationMembershipsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getOrganizationMembershipsCount without sending the request
     */
    async getOrganizationMembershipsCountRequestOpts(requestParameters: GetOrganizationMembershipsCountRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling getOrganizationMembershipsCount().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling getOrganizationMembershipsCount().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['excludeAdminAccounts'] != null) {
            queryParameters['excludeAdminAccounts'] = requestParameters['excludeAdminAccounts'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/members/count`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get total number of members of a given organization
     * Get organization members count
     */
    async getOrganizationMembershipsCountRaw(requestParameters: GetOrganizationMembershipsCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const requestOptions = await this.getOrganizationMembershipsCountRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get total number of members of a given organization
     * Get organization members count
     */
    async getOrganizationMembershipsCount(requestParameters: GetOrganizationMembershipsCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.getOrganizationMembershipsCountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for removeOrganizationMember without sending the request
     */
    async removeOrganizationMemberRequestOpts(requestParameters: RemoveOrganizationMemberRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['realm'] == null) {
            throw new runtime.RequiredError(
                'realm',
                'Required parameter "realm" was null or undefined when calling removeOrganizationMember().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling removeOrganizationMember().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling removeOrganizationMember().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("access_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{realm}/orgs/{orgId}/members/{userId}`;
        urlPath = urlPath.replace('{realm}', encodeURIComponent(String(requestParameters['realm'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove the specified user from the specified organization as a member
     * Remove an organization member
     */
    async removeOrganizationMemberRaw(requestParameters: RemoveOrganizationMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.removeOrganizationMemberRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove the specified user from the specified organization as a member
     * Remove an organization member
     */
    async removeOrganizationMember(requestParameters: RemoveOrganizationMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.removeOrganizationMemberRaw(requestParameters, initOverrides);
    }

}
