/* tslint:disable */
/* eslint-disable */
/**
 * Phase Two Admin REST API
 * This is a REST API reference for the Phase Two Keycloak custom resources. These are extensions to the standard [Keycloak Admin REST API](https://www.keycloak.org/docs-api/latest/rest-api/index.html).  ### Base URI format Paths specified in the documentation are relative to the the base URI. - Format: `https://<host>:<port>/auth/realms` - Example: `https://app.phasetwo.io/auth/realms`  ### Authentication Authentication is achieved by using the `Authentication: Bearer <token>` header in all requests. This is either the access token received from a normal authentication, or by a request directly to the OpenID Connect token endpoint.  It is recommended that you use a Keycloak Admin Client, such as [this one for Javascript](https://github.com/keycloak/keycloak/tree/main/js/libs/keycloak-admin-client), as they take care of authentication, getting an access token, and refreshing it when it expires.  #### Client credentials grant example ``` POST /auth/realms/test-realm/protocol/openid-connect/token Host: app.phasetwo.io Accept: application/json Content-type: application/x-www-form-urlencoded  grant_type=client_credentials&client_id=admin-cli&client_secret=fd649804-3a74-4d69-acaa-8f065c6b7da1 ```  #### Password grant example ``` POST /auth/realms/test-realm/protocol/openid-connect/token Host: app.phasetwo.io Accept: application/json Content-type: application/x-www-form-urlencoded  grant_type=password&username=uname@foo.com&password=pwd123AZY&client_id=admin-cli ```  ### SDKs Modern API libraries are available for several common languages. These are available as open source at the links below, or you can choose to generate your own using our [OpenAPI spec file](https://raw.githubusercontent.com/p2-inc/phasetwo-docs/main/openapi.yaml).  | Language | Library | | --- | --- | | Java (and other JVM langs) | https://github.com/p2-inc/phasetwo-java | | JavaScript/TypeScript | https://github.com/p2-inc/phasetwo-js | | Python | https://github.com/p2-inc/phasetwo-python | 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A freshly issued OIDC token set, reflecting the user's new active organization. The `refresh_token` is only present when the client is configured to use refresh tokens, and `id_token` only for OIDC requests.
 * @export
 * @interface AccessTokenResponse
 */
export interface AccessTokenResponse {
    /**
     * 
     */
    accessToken?: string;
    /**
     * 
     */
    expiresIn?: number;
    /**
     * 
     */
    refreshExpiresIn?: number;
    /**
     * 
     */
    refreshToken?: string;
    /**
     * 
     */
    tokenType?: string;
    /**
     * 
     */
    idToken?: string;
    /**
     * 
     */
    notBeforePolicy?: number;
    /**
     * 
     */
    sessionState?: string;
    /**
     * 
     */
    scope?: string;
}

/**
 * Check if a given object implements the AccessTokenResponse interface.
 */
export function instanceOfAccessTokenResponse(value: object): value is AccessTokenResponse {
    return true;
}

export function AccessTokenResponseFromJSON(json: any): AccessTokenResponse {
    return AccessTokenResponseFromJSONTyped(json, false);
}

export function AccessTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'] == null ? undefined : json['access_token'],
        'expiresIn': json['expires_in'] == null ? undefined : json['expires_in'],
        'refreshExpiresIn': json['refresh_expires_in'] == null ? undefined : json['refresh_expires_in'],
        'refreshToken': json['refresh_token'] == null ? undefined : json['refresh_token'],
        'tokenType': json['token_type'] == null ? undefined : json['token_type'],
        'idToken': json['id_token'] == null ? undefined : json['id_token'],
        'notBeforePolicy': json['not-before-policy'] == null ? undefined : json['not-before-policy'],
        'sessionState': json['session_state'] == null ? undefined : json['session_state'],
        'scope': json['scope'] == null ? undefined : json['scope'],
    };
}

export function AccessTokenResponseToJSON(json: any): AccessTokenResponse {
    return AccessTokenResponseToJSONTyped(json, false);
}

export function AccessTokenResponseToJSONTyped(value?: AccessTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
        'expires_in': value['expiresIn'],
        'refresh_expires_in': value['refreshExpiresIn'],
        'refresh_token': value['refreshToken'],
        'token_type': value['tokenType'],
        'id_token': value['idToken'],
        'not-before-policy': value['notBeforePolicy'],
        'session_state': value['sessionState'],
        'scope': value['scope'],
    };
}

