/* tslint:disable */
/* eslint-disable */
/**
 * Phase Two Admin REST API
 * This is a REST API reference for the Phase Two Keycloak custom resources. These are extensions to the standard [Keycloak Admin REST API](https://www.keycloak.org/docs-api/latest/rest-api/index.html).  ### Base URI format Paths specified in the documentation are relative to the the base URI. - Format: `https://<host>:<port>/auth/realms` - Example: `https://app.phasetwo.io/auth/realms`  ### Authentication Authentication is achieved by using the `Authentication: Bearer <token>` header in all requests. This is either the access token received from a normal authentication, or by a request directly to the OpenID Connect token endpoint.  It is recommended that you use a Keycloak Admin Client, such as [this one for Javascript](https://github.com/keycloak/keycloak/tree/main/js/libs/keycloak-admin-client), as they take care of authentication, getting an access token, and refreshing it when it expires.  #### Client credentials grant example ``` POST /auth/realms/test-realm/protocol/openid-connect/token Host: app.phasetwo.io Accept: application/json Content-type: application/x-www-form-urlencoded  grant_type=client_credentials&client_id=admin-cli&client_secret=fd649804-3a74-4d69-acaa-8f065c6b7da1 ```  #### Password grant example ``` POST /auth/realms/test-realm/protocol/openid-connect/token Host: app.phasetwo.io Accept: application/json Content-type: application/x-www-form-urlencoded  grant_type=password&username=uname@foo.com&password=pwd123AZY&client_id=admin-cli ```  ### SDKs Modern API libraries are available for several common languages. These are available as open source at the links below, or you can choose to generate your own using our [OpenAPI spec file](https://raw.githubusercontent.com/p2-inc/phasetwo-docs/main/openapi.yaml).  | Language | Library | | --- | --- | | Java (and other JVM langs) | https://github.com/p2-inc/phasetwo-java | | JavaScript/TypeScript | https://github.com/p2-inc/phasetwo-js | | Python | https://github.com/p2-inc/phasetwo-python | 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * HTTP Basic auth. The password is hashed with Argon2id before
 * storage.
 * 
 * @export
 * @interface ExternalBasicScimAuth
 */
export interface ExternalBasicScimAuth {
    /**
     * 
     */
    type: ExternalBasicScimAuthTypeEnum;
    /**
     * Username for HTTP Basic auth. Stored in cleartext.
     */
    username?: string;
    /**
     * Password for HTTP Basic auth. Cleartext on submit; hashed at
     * rest. Omit on update to keep the existing password.
     * 
     */
    password?: string;
}


/**
 * @export
 */
export const ExternalBasicScimAuthTypeEnum = {
    ExternalBasic: 'EXTERNAL_BASIC',
} as const;
export type ExternalBasicScimAuthTypeEnum = typeof ExternalBasicScimAuthTypeEnum[keyof typeof ExternalBasicScimAuthTypeEnum];


/**
 * Check if a given object implements the ExternalBasicScimAuth interface.
 */
export function instanceOfExternalBasicScimAuth(value: object): value is ExternalBasicScimAuth {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'EXTERNAL_BASIC') return false;
    
    return true;
}

export function ExternalBasicScimAuthFromJSON(json: any): ExternalBasicScimAuth {
    return ExternalBasicScimAuthFromJSONTyped(json, false);
}

export function ExternalBasicScimAuthFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalBasicScimAuth {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'username': json['username'] == null ? undefined : json['username'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function ExternalBasicScimAuthToJSON(json: any): ExternalBasicScimAuth {
    return ExternalBasicScimAuthToJSONTyped(json, false);
}

export function ExternalBasicScimAuthToJSONTyped(value?: ExternalBasicScimAuth | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'username': value['username'],
        'password': value['password'],
    };
}

