/* tslint:disable */
/* eslint-disable */
/**
 * Phase Two Admin REST API
 * This is a REST API reference for the Phase Two Keycloak custom resources. These are extensions to the standard [Keycloak Admin REST API](https://www.keycloak.org/docs-api/latest/rest-api/index.html).  ### Base URI format Paths specified in the documentation are relative to the the base URI. - Format: `https://<host>:<port>/auth/realms` - Example: `https://app.phasetwo.io/auth/realms`  ### Authentication Authentication is achieved by using the `Authentication: Bearer <token>` header in all requests. This is either the access token received from a normal authentication, or by a request directly to the OpenID Connect token endpoint.  It is recommended that you use a Keycloak Admin Client, such as [this one for Javascript](https://github.com/keycloak/keycloak/tree/main/js/libs/keycloak-admin-client), as they take care of authentication, getting an access token, and refreshing it when it expires.  #### Client credentials grant example ``` POST /auth/realms/test-realm/protocol/openid-connect/token Host: app.phasetwo.io Accept: application/json Content-type: application/x-www-form-urlencoded  grant_type=client_credentials&client_id=admin-cli&client_secret=fd649804-3a74-4d69-acaa-8f065c6b7da1 ```  #### Password grant example ``` POST /auth/realms/test-realm/protocol/openid-connect/token Host: app.phasetwo.io Accept: application/json Content-type: application/x-www-form-urlencoded  grant_type=password&username=uname@foo.com&password=pwd123AZY&client_id=admin-cli ```  ### SDKs Modern API libraries are available for several common languages. These are available as open source at the links below, or you can choose to generate your own using our [OpenAPI spec file](https://raw.githubusercontent.com/p2-inc/phasetwo-docs/main/openapi.yaml).  | Language | Library | | --- | --- | | Java (and other JVM langs) | https://github.com/p2-inc/phasetwo-java | | JavaScript/TypeScript | https://github.com/p2-inc/phasetwo-js | | Python | https://github.com/p2-inc/phasetwo-python | 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MagicLinkRequest
 */
export interface MagicLinkRequest {
    /**
     * 
     */
    email?: string;
    /**
     * 
     */
    clientId: string;
    /**
     * 
     */
    redirectUri: string;
    /**
     * 
     */
    username?: string;
    /**
     * 
     */
    expirationSeconds?: number;
    /**
     * 
     */
    forceCreate?: boolean;
    /**
     * 
     */
    sendEmail?: boolean;
    /**
     * 
     */
    updateProfile?: boolean;
    /**
     * 
     */
    updatePassword?: boolean;
    /**
     * 
     */
    scope?: string;
    /**
     * 
     */
    nonce?: string;
    /**
     * 
     */
    state?: string;
    /**
     * 
     */
    codeChallenge?: string;
    /**
     * 
     */
    codeChallengeMethod?: string;
    /**
     * 
     */
    rememberMe?: boolean;
    /**
     * 
     */
    reusable?: boolean;
    /**
     * 
     */
    responseMode?: string;
}

/**
 * Check if a given object implements the MagicLinkRequest interface.
 */
export function instanceOfMagicLinkRequest(value: object): value is MagicLinkRequest {
    if ((!('clientId' in (value as Record<string, any>)) && !('client_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['clientId'] === undefined && (value as Record<string, any>)['client_id'] === undefined)) return false;
    if ((!('redirectUri' in (value as Record<string, any>)) && !('redirect_uri' in (value as Record<string, any>))) || ((value as Record<string, any>)['redirectUri'] === undefined && (value as Record<string, any>)['redirect_uri'] === undefined)) return false;
    return true;
}

export function MagicLinkRequestFromJSON(json: any): MagicLinkRequest {
    return MagicLinkRequestFromJSONTyped(json, false);
}

export function MagicLinkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MagicLinkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'clientId': json['client_id'],
        'redirectUri': json['redirect_uri'],
        'username': json['username'] == null ? undefined : json['username'],
        'expirationSeconds': json['expiration_seconds'] == null ? undefined : json['expiration_seconds'],
        'forceCreate': json['force_create'] == null ? undefined : json['force_create'],
        'sendEmail': json['send_email'] == null ? undefined : json['send_email'],
        'updateProfile': json['update_profile'] == null ? undefined : json['update_profile'],
        'updatePassword': json['update_password'] == null ? undefined : json['update_password'],
        'scope': json['scope'] == null ? undefined : json['scope'],
        'nonce': json['nonce'] == null ? undefined : json['nonce'],
        'state': json['state'] == null ? undefined : json['state'],
        'codeChallenge': json['code_challenge'] == null ? undefined : json['code_challenge'],
        'codeChallengeMethod': json['code_challenge_method'] == null ? undefined : json['code_challenge_method'],
        'rememberMe': json['remember_me'] == null ? undefined : json['remember_me'],
        'reusable': json['reusable'] == null ? undefined : json['reusable'],
        'responseMode': json['response_mode'] == null ? undefined : json['response_mode'],
    };
}

export function MagicLinkRequestToJSON(json: any): MagicLinkRequest {
    return MagicLinkRequestToJSONTyped(json, false);
}

export function MagicLinkRequestToJSONTyped(value?: MagicLinkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'client_id': value['clientId'],
        'redirect_uri': value['redirectUri'],
        'username': value['username'],
        'expiration_seconds': value['expirationSeconds'],
        'force_create': value['forceCreate'],
        'send_email': value['sendEmail'],
        'update_profile': value['updateProfile'],
        'update_password': value['updatePassword'],
        'scope': value['scope'],
        'nonce': value['nonce'],
        'state': value['state'],
        'code_challenge': value['codeChallenge'],
        'code_challenge_method': value['codeChallengeMethod'],
        'remember_me': value['rememberMe'],
        'reusable': value['reusable'],
        'response_mode': value['responseMode'],
    };
}

