/* tslint:disable */
/* eslint-disable */
/**
 * Phase Two Admin REST API
 * This is a REST API reference for the Phase Two Keycloak custom resources. These are extensions to the standard [Keycloak Admin REST API](https://www.keycloak.org/docs-api/latest/rest-api/index.html).  ### Base URI format Paths specified in the documentation are relative to the the base URI. - Format: `https://<host>:<port>/auth/realms` - Example: `https://app.phasetwo.io/auth/realms`  ### Authentication Authentication is achieved by using the `Authentication: Bearer <token>` header in all requests. This is either the access token received from a normal authentication, or by a request directly to the OpenID Connect token endpoint.  It is recommended that you use a Keycloak Admin Client, such as [this one for Javascript](https://github.com/keycloak/keycloak/tree/main/js/libs/keycloak-admin-client), as they take care of authentication, getting an access token, and refreshing it when it expires.  #### Client credentials grant example ``` POST /auth/realms/test-realm/protocol/openid-connect/token Host: app.phasetwo.io Accept: application/json Content-type: application/x-www-form-urlencoded  grant_type=client_credentials&client_id=admin-cli&client_secret=fd649804-3a74-4d69-acaa-8f065c6b7da1 ```  #### Password grant example ``` POST /auth/realms/test-realm/protocol/openid-connect/token Host: app.phasetwo.io Accept: application/json Content-type: application/x-www-form-urlencoded  grant_type=password&username=uname@foo.com&password=pwd123AZY&client_id=admin-cli ```  ### SDKs Modern API libraries are available for several common languages. These are available as open source at the links below, or you can choose to generate your own using our [OpenAPI spec file](https://raw.githubusercontent.com/p2-inc/phasetwo-docs/main/openapi.yaml).  | Language | Library | | --- | --- | | Java (and other JVM langs) | https://github.com/p2-inc/phasetwo-java | | JavaScript/TypeScript | https://github.com/p2-inc/phasetwo-js | | Python | https://github.com/p2-inc/phasetwo-python | 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { ExternalBasicScimAuth } from './ExternalBasicScimAuth';
import {
    instanceOfExternalBasicScimAuth,
    ExternalBasicScimAuthFromJSON,
    ExternalBasicScimAuthFromJSONTyped,
    ExternalBasicScimAuthToJSON,
} from './ExternalBasicScimAuth';
import type { ExternalJwtScimAuth } from './ExternalJwtScimAuth';
import {
    instanceOfExternalJwtScimAuth,
    ExternalJwtScimAuthFromJSON,
    ExternalJwtScimAuthFromJSONTyped,
    ExternalJwtScimAuthToJSON,
} from './ExternalJwtScimAuth';
import type { ExternalSecretScimAuth } from './ExternalSecretScimAuth';
import {
    instanceOfExternalSecretScimAuth,
    ExternalSecretScimAuthFromJSON,
    ExternalSecretScimAuthFromJSONTyped,
    ExternalSecretScimAuthToJSON,
} from './ExternalSecretScimAuth';
import type { KeycloakScimAuth } from './KeycloakScimAuth';
import {
    instanceOfKeycloakScimAuth,
    KeycloakScimAuthFromJSON,
    KeycloakScimAuthFromJSONTyped,
    KeycloakScimAuthToJSON,
} from './KeycloakScimAuth';

/**
 * @type OrganizationScimAuth
 * Polymorphic authentication configuration for the inbound SCIM
 * endpoint. The `type` field discriminates the variant; the remaining
 * fields depend on the variant chosen.
 * 
 * @export
 */
export type OrganizationScimAuth = { type: 'EXTERNAL_BASIC' } & ExternalBasicScimAuth | { type: 'EXTERNAL_JWT' } & ExternalJwtScimAuth | { type: 'EXTERNAL_SECRET' } & ExternalSecretScimAuth | { type: 'KEYCLOAK' } & KeycloakScimAuth;

export function OrganizationScimAuthFromJSON(json: any): OrganizationScimAuth {
    return OrganizationScimAuthFromJSONTyped(json, false);
}

export function OrganizationScimAuthFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationScimAuth {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'EXTERNAL_BASIC':
            return Object.assign({}, ExternalBasicScimAuthFromJSONTyped(json, true), { type: 'EXTERNAL_BASIC' } as const);
        case 'EXTERNAL_JWT':
            return Object.assign({}, ExternalJwtScimAuthFromJSONTyped(json, true), { type: 'EXTERNAL_JWT' } as const);
        case 'EXTERNAL_SECRET':
            return Object.assign({}, ExternalSecretScimAuthFromJSONTyped(json, true), { type: 'EXTERNAL_SECRET' } as const);
        case 'KEYCLOAK':
            return Object.assign({}, KeycloakScimAuthFromJSONTyped(json, true), { type: 'KEYCLOAK' } as const);
        default:
            return json;
    }
}

export function OrganizationScimAuthToJSON(json: any): any {
    return OrganizationScimAuthToJSONTyped(json, false);
}

export function OrganizationScimAuthToJSONTyped(value?: OrganizationScimAuth | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'EXTERNAL_BASIC':
            return Object.assign({}, ExternalBasicScimAuthToJSON(value), { 'type': 'EXTERNAL_BASIC' } as const);
        case 'EXTERNAL_JWT':
            return Object.assign({}, ExternalJwtScimAuthToJSON(value), { 'type': 'EXTERNAL_JWT' } as const);
        case 'EXTERNAL_SECRET':
            return Object.assign({}, ExternalSecretScimAuthToJSON(value), { 'type': 'EXTERNAL_SECRET' } as const);
        case 'KEYCLOAK':
            return Object.assign({}, KeycloakScimAuthToJSON(value), { 'type': 'KEYCLOAK' } as const);
        default:
            return value;
    }
}

