/* tslint:disable */
/* eslint-disable */
/**
 * Phase Two Admin REST API
 * This is a REST API reference for the Phase Two Keycloak custom resources. These are extensions to the standard [Keycloak Admin REST API](https://www.keycloak.org/docs-api/latest/rest-api/index.html).  ### Base URI format Paths specified in the documentation are relative to the the base URI. - Format: `https://<host>:<port>/auth/realms` - Example: `https://app.phasetwo.io/auth/realms`  ### Authentication Authentication is achieved by using the `Authentication: Bearer <token>` header in all requests. This is either the access token received from a normal authentication, or by a request directly to the OpenID Connect token endpoint.  It is recommended that you use a Keycloak Admin Client, such as [this one for Javascript](https://github.com/keycloak/keycloak/tree/main/js/libs/keycloak-admin-client), as they take care of authentication, getting an access token, and refreshing it when it expires.  #### Client credentials grant example ``` POST /auth/realms/test-realm/protocol/openid-connect/token Host: app.phasetwo.io Accept: application/json Content-type: application/x-www-form-urlencoded  grant_type=client_credentials&client_id=admin-cli&client_secret=fd649804-3a74-4d69-acaa-8f065c6b7da1 ```  #### Password grant example ``` POST /auth/realms/test-realm/protocol/openid-connect/token Host: app.phasetwo.io Accept: application/json Content-type: application/x-www-form-urlencoded  grant_type=password&username=uname@foo.com&password=pwd123AZY&client_id=admin-cli ```  ### SDKs Modern API libraries are available for several common languages. These are available as open source at the links below, or you can choose to generate your own using our [OpenAPI spec file](https://raw.githubusercontent.com/p2-inc/phasetwo-docs/main/openapi.yaml).  | Language | Library | | --- | --- | | Java (and other JVM langs) | https://github.com/p2-inc/phasetwo-java | | JavaScript/TypeScript | https://github.com/p2-inc/phasetwo-js | | Python | https://github.com/p2-inc/phasetwo-python | 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { OrganizationExportRepresentation } from './OrganizationExportRepresentation';
import {
    OrganizationExportRepresentationFromJSON,
    OrganizationExportRepresentationFromJSONTyped,
    OrganizationExportRepresentationToJSON,
    OrganizationExportRepresentationToJSONTyped,
} from './OrganizationExportRepresentation';
import type { OrganizationsConfigRepresentation } from './OrganizationsConfigRepresentation';
import {
    OrganizationsConfigRepresentationFromJSON,
    OrganizationsConfigRepresentationFromJSONTyped,
    OrganizationsConfigRepresentationToJSON,
    OrganizationsConfigRepresentationToJSONTyped,
} from './OrganizationsConfigRepresentation';

/**
 * 
 * @export
 * @interface OrganizationsExportRepresentation
 */
export interface OrganizationsExportRepresentation {
    /**
     * Export format version
     */
    version?: string;
    /**
     * Source realm name
     */
    realm?: string;
    /**
     * Export timestamp
     */
    exportedAt?: Date;
    /**
     * 
     */
    organizations?: Array<OrganizationExportRepresentation>;
    /**
     * 
     */
    config?: OrganizationsConfigRepresentation;
}

/**
 * Check if a given object implements the OrganizationsExportRepresentation interface.
 */
export function instanceOfOrganizationsExportRepresentation(value: object): value is OrganizationsExportRepresentation {
    return true;
}

export function OrganizationsExportRepresentationFromJSON(json: any): OrganizationsExportRepresentation {
    return OrganizationsExportRepresentationFromJSONTyped(json, false);
}

export function OrganizationsExportRepresentationFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationsExportRepresentation {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'] == null ? undefined : json['version'],
        'realm': json['realm'] == null ? undefined : json['realm'],
        'exportedAt': json['exportedAt'] == null ? undefined : (parseDateTime(json['exportedAt'])),
        'organizations': json['organizations'] == null ? undefined : ((json['organizations'] as Array<any>).map(OrganizationExportRepresentationFromJSON)),
        'config': json['config'] == null ? undefined : OrganizationsConfigRepresentationFromJSON(json['config']),
    };
}

export function OrganizationsExportRepresentationToJSON(json: any): OrganizationsExportRepresentation {
    return OrganizationsExportRepresentationToJSONTyped(json, false);
}

export function OrganizationsExportRepresentationToJSONTyped(value?: OrganizationsExportRepresentation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'realm': value['realm'],
        'exportedAt': value['exportedAt'] == null ? value['exportedAt'] : serializeDateTime(value['exportedAt']),
        'organizations': value['organizations'] == null ? undefined : ((value['organizations'] as Array<any>).map(OrganizationExportRepresentationToJSON)),
        'config': OrganizationsConfigRepresentationToJSON(value['config']),
    };
}

