/* tslint:disable */
/* eslint-disable */
/**
 * Phase Two Admin REST API
 * This is a REST API reference for the Phase Two Keycloak custom resources. These are extensions to the standard [Keycloak Admin REST API](https://www.keycloak.org/docs-api/latest/rest-api/index.html).  ### Base URI format Paths specified in the documentation are relative to the the base URI. - Format: `https://<host>:<port>/auth/realms` - Example: `https://app.phasetwo.io/auth/realms`  ### Authentication Authentication is achieved by using the `Authentication: Bearer <token>` header in all requests. This is either the access token received from a normal authentication, or by a request directly to the OpenID Connect token endpoint.  It is recommended that you use a Keycloak Admin Client, such as [this one for Javascript](https://github.com/keycloak/keycloak/tree/main/js/libs/keycloak-admin-client), as they take care of authentication, getting an access token, and refreshing it when it expires.  #### Client credentials grant example ``` POST /auth/realms/test-realm/protocol/openid-connect/token Host: app.phasetwo.io Accept: application/json Content-type: application/x-www-form-urlencoded  grant_type=client_credentials&client_id=admin-cli&client_secret=fd649804-3a74-4d69-acaa-8f065c6b7da1 ```  #### Password grant example ``` POST /auth/realms/test-realm/protocol/openid-connect/token Host: app.phasetwo.io Accept: application/json Content-type: application/x-www-form-urlencoded  grant_type=password&username=uname@foo.com&password=pwd123AZY&client_id=admin-cli ```  ### SDKs Modern API libraries are available for several common languages. These are available as open source at the links below, or you can choose to generate your own using our [OpenAPI spec file](https://raw.githubusercontent.com/p2-inc/phasetwo-docs/main/openapi.yaml).  | Language | Library | | --- | --- | | Java (and other JVM langs) | https://github.com/p2-inc/phasetwo-java | | JavaScript/TypeScript | https://github.com/p2-inc/phasetwo-js | | Python | https://github.com/p2-inc/phasetwo-python | 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizationRoleRepresentation } from './OrganizationRoleRepresentation';
import {
    OrganizationRoleRepresentationFromJSON,
    OrganizationRoleRepresentationFromJSONTyped,
    OrganizationRoleRepresentationToJSON,
    OrganizationRoleRepresentationToJSONTyped,
} from './OrganizationRoleRepresentation';
import type { IdentityProviderRepresentation } from './IdentityProviderRepresentation';
import {
    IdentityProviderRepresentationFromJSON,
    IdentityProviderRepresentationFromJSONTyped,
    IdentityProviderRepresentationToJSON,
    IdentityProviderRepresentationToJSONTyped,
} from './IdentityProviderRepresentation';
import type { OrganizationExportRepresentationAllOfMembers } from './OrganizationExportRepresentationAllOfMembers';
import {
    OrganizationExportRepresentationAllOfMembersFromJSON,
    OrganizationExportRepresentationAllOfMembersFromJSONTyped,
    OrganizationExportRepresentationAllOfMembersToJSON,
    OrganizationExportRepresentationAllOfMembersToJSONTyped,
} from './OrganizationExportRepresentationAllOfMembers';

/**
 * 
 * @export
 * @interface OrganizationExportRepresentation
 */
export interface OrganizationExportRepresentation {
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    name?: string;
    /**
     * 
     */
    displayName?: string;
    /**
     * 
     */
    url?: string;
    /**
     * 
     */
    realm?: string;
    /**
     * 
     */
    domains?: Array<string>;
    /**
     * 
     */
    attributes?: { [key: string]: Array<string>; };
    /**
     * 
     */
    roles?: Array<OrganizationRoleRepresentation>;
    /**
     * 
     */
    identityProviders?: Array<IdentityProviderRepresentation>;
    /**
     * 
     */
    members?: Array<OrganizationExportRepresentationAllOfMembers>;
}

/**
 * Check if a given object implements the OrganizationExportRepresentation interface.
 */
export function instanceOfOrganizationExportRepresentation(value: object): value is OrganizationExportRepresentation {
    return true;
}

export function OrganizationExportRepresentationFromJSON(json: any): OrganizationExportRepresentation {
    return OrganizationExportRepresentationFromJSONTyped(json, false);
}

export function OrganizationExportRepresentationFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationExportRepresentation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'url': json['url'] == null ? undefined : json['url'],
        'realm': json['realm'] == null ? undefined : json['realm'],
        'domains': json['domains'] == null ? undefined : json['domains'],
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
        'roles': json['roles'] == null ? undefined : ((json['roles'] as Array<any>).map(OrganizationRoleRepresentationFromJSON)),
        'identityProviders': json['identityProviders'] == null ? undefined : ((json['identityProviders'] as Array<any>).map(IdentityProviderRepresentationFromJSON)),
        'members': json['members'] == null ? undefined : ((json['members'] as Array<any>).map(OrganizationExportRepresentationAllOfMembersFromJSON)),
    };
}

export function OrganizationExportRepresentationToJSON(json: any): OrganizationExportRepresentation {
    return OrganizationExportRepresentationToJSONTyped(json, false);
}

export function OrganizationExportRepresentationToJSONTyped(value?: OrganizationExportRepresentation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'displayName': value['displayName'],
        'url': value['url'],
        'realm': value['realm'],
        'domains': value['domains'],
        'attributes': value['attributes'],
        'roles': value['roles'] == null ? undefined : ((value['roles'] as Array<any>).map(OrganizationRoleRepresentationToJSON)),
        'identityProviders': value['identityProviders'] == null ? undefined : ((value['identityProviders'] as Array<any>).map(IdentityProviderRepresentationToJSON)),
        'members': value['members'] == null ? undefined : ((value['members'] as Array<any>).map(OrganizationExportRepresentationAllOfMembersToJSON)),
    };
}

