/* tslint:disable */
/* eslint-disable */
/**
 * Phase Two Admin REST API
 * This is a REST API reference for the Phase Two Keycloak custom resources. These are extensions to the standard [Keycloak Admin REST API](https://www.keycloak.org/docs-api/17.0/rest-api/index.html).  ### Base URI format Paths specified in the documentation are relative to the the base URI. - Format: `https://<host>:<port>/auth/realms` - Example: `https://app.phasetwo.io/auth/realms`  ### Authentication Authentication is achieved by using the `Authentication: Bearer <token>` header in all requests. This is either the access token received from a normal authentication, or by a request directly to the OpenID Connect token endpoint.  It is recommended that you use a Keycloak Admin Client, such as [this one for Javascript](https://github.com/keycloak/keycloak-nodejs-admin-client), as they take care of authentication, getting an access token, and refreshing it when it expires.  #### Client credentials grant example ``` POST /auth/realms/test-realm/protocol/openid-connect/token Host: app.phasetwo.io Accept: application/json Content-type: application/x-www-form-urlencoded  grant_type=client_credentials&client_id=admin-cli&client_secret=fd649804-3a74-4d69-acaa-8f065c6b7da1 ```  #### Password grant example ``` POST /auth/realms/test-realm/protocol/openid-connect/token Host: app.phasetwo.io Accept: application/json Content-type: application/x-www-form-urlencoded  grant_type=password&username=uname@foo.com&password=pwd123AZY&client_id=admin-cli ```  ### SDKs Modern API libraries are available for several common languages. These are available as open source at the links below, or you can choose to generate your own using our [OpenAPI spec file](https://raw.githubusercontent.com/p2-inc/phasetwo-docs/master/openapi.yaml).  | Language | Library | | --- | --- | | Java (and other JVM langs) | https://github.com/p2-inc/phasetwo-java | | JavaScript/TypeScript | https://github.com/p2-inc/phasetwo-js | | Python | https://github.com/p2-inc/phasetwo-python | 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookRepresentation
 */
export interface WebhookRepresentation {
    /**
     * 
     * @type {object}
     * @memberof WebhookRepresentation
     */
    attributes?: object;
    /**
     * 
     * @type {string}
     * @memberof WebhookRepresentation
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WebhookRepresentation
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof WebhookRepresentation
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookRepresentation
     */
    secret?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookRepresentation
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookRepresentation
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookRepresentation
     */
    realm?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof WebhookRepresentation
     */
    eventTypes?: Array<string>;
}

/**
 * Check if a given object implements the WebhookRepresentation interface.
 */
export function instanceOfWebhookRepresentation(value: object): value is WebhookRepresentation {
    return true;
}

export function WebhookRepresentationFromJSON(json: any): WebhookRepresentation {
    return WebhookRepresentationFromJSONTyped(json, false);
}

export function WebhookRepresentationFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookRepresentation {
    if (json == null) {
        return json;
    }
    return {
        
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
        'id': json['id'] == null ? undefined : json['id'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'url': json['url'] == null ? undefined : json['url'],
        'secret': json['secret'] == null ? undefined : json['secret'],
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'realm': json['realm'] == null ? undefined : json['realm'],
        'eventTypes': json['eventTypes'] == null ? undefined : json['eventTypes'],
    };
}

  export function WebhookRepresentationToJSON(json: any): WebhookRepresentation {
      return WebhookRepresentationToJSONTyped(json, false);
  }

  export function WebhookRepresentationToJSONTyped(value?: WebhookRepresentation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attributes': value['attributes'],
        'id': value['id'],
        'enabled': value['enabled'],
        'url': value['url'],
        'secret': value['secret'],
        'createdBy': value['createdBy'],
        'createdAt': value['createdAt'],
        'realm': value['realm'],
        'eventTypes': value['eventTypes'],
    };
}

