/* tslint:disable */
/* eslint-disable */
/**
 * Phase Two Admin REST API
 * This is a REST API reference for the Phase Two Keycloak custom resources. These are extensions to the standard [Keycloak Admin REST API](https://www.keycloak.org/docs-api/latest/rest-api/index.html).  ### Base URI format Paths specified in the documentation are relative to the the base URI. - Format: `https://<host>:<port>/auth/realms` - Example: `https://app.phasetwo.io/auth/realms`  ### Authentication Authentication is achieved by using the `Authentication: Bearer <token>` header in all requests. This is either the access token received from a normal authentication, or by a request directly to the OpenID Connect token endpoint.  It is recommended that you use a Keycloak Admin Client, such as [this one for Javascript](https://github.com/keycloak/keycloak/tree/main/js/libs/keycloak-admin-client), as they take care of authentication, getting an access token, and refreshing it when it expires.  #### Client credentials grant example ``` POST /auth/realms/test-realm/protocol/openid-connect/token Host: app.phasetwo.io Accept: application/json Content-type: application/x-www-form-urlencoded  grant_type=client_credentials&client_id=admin-cli&client_secret=fd649804-3a74-4d69-acaa-8f065c6b7da1 ```  #### Password grant example ``` POST /auth/realms/test-realm/protocol/openid-connect/token Host: app.phasetwo.io Accept: application/json Content-type: application/x-www-form-urlencoded  grant_type=password&username=uname@foo.com&password=pwd123AZY&client_id=admin-cli ```  ### SDKs Modern API libraries are available for several common languages. These are available as open source at the links below, or you can choose to generate your own using our [OpenAPI spec file](https://raw.githubusercontent.com/p2-inc/phasetwo-docs/main/openapi.yaml).  | Language | Library | | --- | --- | | Java (and other JVM langs) | https://github.com/p2-inc/phasetwo-java | | JavaScript/TypeScript | https://github.com/p2-inc/phasetwo-js | | Python | https://github.com/p2-inc/phasetwo-python | 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookRepresentation } from './WebhookRepresentation';
import {
    WebhookRepresentationFromJSON,
    WebhookRepresentationFromJSONTyped,
    WebhookRepresentationToJSON,
    WebhookRepresentationToJSONTyped,
} from './WebhookRepresentation';

/**
 * 
 * @export
 * @interface WebhookSendRepresentation
 */
export interface WebhookSendRepresentation {
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    type?: string;
    /**
     * 
     */
    status?: number;
    /**
     * 
     */
    statusMessage?: string;
    /**
     * 
     */
    retried?: number;
    /**
     * 
     */
    sentAt?: string;
    /**
     * 
     */
    eventId?: string;
    /**
     * 
     */
    keycloakEventType?: string;
    /**
     * 
     */
    keycloakEventId?: string;
    /**
     * 
     */
    webhook?: WebhookRepresentation;
    /**
     * 
     */
    payload?: string;
}

/**
 * Check if a given object implements the WebhookSendRepresentation interface.
 */
export function instanceOfWebhookSendRepresentation(value: object): value is WebhookSendRepresentation {
    return true;
}

export function WebhookSendRepresentationFromJSON(json: any): WebhookSendRepresentation {
    return WebhookSendRepresentationFromJSONTyped(json, false);
}

export function WebhookSendRepresentationFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookSendRepresentation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'status': json['status'] == null ? undefined : json['status'],
        'statusMessage': json['status_message'] == null ? undefined : json['status_message'],
        'retried': json['retried'] == null ? undefined : json['retried'],
        'sentAt': json['sent_at'] == null ? undefined : json['sent_at'],
        'eventId': json['event_id'] == null ? undefined : json['event_id'],
        'keycloakEventType': json['keycloak_event_type'] == null ? undefined : json['keycloak_event_type'],
        'keycloakEventId': json['keycloak_event_id'] == null ? undefined : json['keycloak_event_id'],
        'webhook': json['webhook'] == null ? undefined : WebhookRepresentationFromJSON(json['webhook']),
        'payload': json['payload'] == null ? undefined : json['payload'],
    };
}

export function WebhookSendRepresentationToJSON(json: any): WebhookSendRepresentation {
    return WebhookSendRepresentationToJSONTyped(json, false);
}

export function WebhookSendRepresentationToJSONTyped(value?: WebhookSendRepresentation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'status': value['status'],
        'status_message': value['statusMessage'],
        'retried': value['retried'],
        'sent_at': value['sentAt'],
        'event_id': value['eventId'],
        'keycloak_event_type': value['keycloakEventType'],
        'keycloak_event_id': value['keycloakEventId'],
        'webhook': WebhookRepresentationToJSON(value['webhook']),
        'payload': value['payload'],
    };
}

