server:
  port: 8081
spring:
  application:
    name: idp-initiated
  security:
    saml2:
      relyingparty:
        registration:
          keycloak:
            entity-id: "{baseUrl}/saml2/metadata"
            acs:
              location: "{baseUrl}/login/saml2/sso"
            singlelogout:
              url: "{baseUrl}/logout/saml2/slo"
            signing:
              credentials:
                - private-key-location: file:credentials/private.key
                  certificate-location: file:credentials/cert.crt
            assertingparty:
              metadata-uri: http://localhost:8080/realms/test-realm/protocol/saml/descriptor
