version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_RELATIVE_PATH=/auth/
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=*:8787,server=y,suspend=n -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true
    ports:
      - "8888:8080"
    restart: always
