name: Deploy to Vercel

on:
  push:
    branches:
      - main
    paths:
      - "frameworks/nextjs/**"
  pull_request:
    branches:
      - main
    paths:
      - "frameworks/nextjs/**"

jobs:
  deploy-preview:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
        working-directory: ./frameworks/nextjs

      - name: Build project
        run: npm run build
        working-directory: ./frameworks/nextjs

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_DEPLOYMENT_TOKEN }}
        run: vercel -t $VERCEL_TOKEN -n phasetwo-nextjs-example
        working-directory: ./frameworks/nextjs

  deploy-prod:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
        working-directory: ./frameworks/nextjs

      - name: Build project
        run: npm run build
        working-directory: ./frameworks/nextjs

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_DEPLOYMENT_TOKEN }}
        run: vercel --prod -t $VERCEL_TOKEN -n phasetwo-nextjs-example
        working-directory: ./frameworks/nextjs
