name: Nuxt (keycloak-js)

on:
  push:
    branches: [main]
    paths:
      - "frameworks/nuxt/keycloak-js/**"
      - ".github/workflows/nuxt-keycloakjs.yml"
  pull_request:
    branches: [main]
    paths:
      - "frameworks/nuxt/keycloak-js/**"
      - ".github/workflows/nuxt-keycloakjs.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  ci:
    uses: ./.github/workflows/_node-ci.yml
    with:
      working-directory: frameworks/nuxt/keycloak-js

  deploy:
    needs: ci
    uses: ./.github/workflows/_vercel-deploy.yml
    with:
      working-directory: frameworks/nuxt/keycloak-js
    secrets:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_NUXT_KEYCLOAKJS_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_DEPLOYMENT_TOKEN }}
