name: Deploy Nuxt keycloak-js Example
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_NUXT_KEYCLOAKJS_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_DEPLOYMENT_TOKEN }}
on:
  push:
    branches:
      - main
    paths:
      - "frameworks/nuxt/keycloak-js/**"
  pull_request:
    branches:
      - main
    paths:
      - "frameworks/nuxt/keycloak-js/**"

jobs:
  deploy-preview:
    if: github.event_name == 'pull_request' && github.repository == 'p2-inc/examples'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
        working-directory: ./frameworks/nuxt/keycloak-js

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
        working-directory: ./frameworks/nuxt/keycloak-js

      - name: Build Project Artifacts
        run: vercel build --token=$VERCEL_TOKEN
        working-directory: ./frameworks/nuxt/keycloak-js

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=$VERCEL_TOKEN
        working-directory: ./frameworks/nuxt/keycloak-js

  deploy-prod:
    if: github.event_name == 'push' && github.repository == 'p2-inc/examples'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
        working-directory: ./frameworks/nuxt/keycloak-js

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=$VERCEL_TOKEN
        working-directory: ./frameworks/nuxt/keycloak-js

      - name: Build Project Artifacts
        run: vercel build --prod --token=$VERCEL_TOKEN
        working-directory: ./frameworks/nuxt/keycloak-js

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
        working-directory: ./frameworks/nuxt/keycloak-js
