name: Nuxt (oidc-client-ts)

on:
  push:
    branches: [main]
    paths:
      - "frameworks/nuxt/oidc-client-ts/**"
      - ".github/workflows/nuxt-oidc.yml"
  pull_request:
    branches: [main]
    paths:
      - "frameworks/nuxt/oidc-client-ts/**"
      - ".github/workflows/nuxt-oidc.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  ci:
    uses: ./.github/workflows/_node-ci.yml
    with:
      working-directory: frameworks/nuxt/oidc-client-ts

  deploy:
    needs: ci
    uses: ./.github/workflows/_vercel-deploy.yml
    with:
      working-directory: frameworks/nuxt/oidc-client-ts
    secrets:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_NUXT_OIDC_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_DEPLOYMENT_TOKEN }}
