name: React (oidc-spa)

on:
  push:
    branches: [main]
    paths:
      - "frameworks/reactjs/oidc-spa/**"
      - ".github/workflows/react-oidcspa.yml"
  pull_request:
    branches: [main]
    paths:
      - "frameworks/reactjs/oidc-spa/**"
      - ".github/workflows/react-oidcspa.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  ci:
    uses: ./.github/workflows/_node-ci.yml
    with:
      working-directory: frameworks/reactjs/oidc-spa

  deploy:
    needs: ci
    uses: ./.github/workflows/_vercel-deploy.yml
    with:
      working-directory: frameworks/reactjs/oidc-spa
    secrets:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_REACT_OIDCSPA_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_DEPLOYMENT_TOKEN }}
