name: React Router v7, formerly Remix (remix-auth)

on:
  push:
    branches: [main]
    paths:
      - "frameworks/remix/**"
      - ".github/workflows/remix.yml"
  pull_request:
    branches: [main]
    paths:
      - "frameworks/remix/**"
      - ".github/workflows/remix.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  ci:
    uses: ./.github/workflows/_node-ci.yml
    with:
      working-directory: frameworks/remix

  deploy:
    needs: ci
    uses: ./.github/workflows/_vercel-deploy.yml
    with:
      working-directory: frameworks/remix
    secrets:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_REMIX_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_DEPLOYMENT_TOKEN }}
